- id: '1675371731836'
  alias: Remote - office
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: c50534a46a69819899bb017cf8a173b5
      action_button_up_short:
      - service: light.turn_on
        data: {}
        target:
          device_id: 14ddd32c9da6f63ca83b15c67893d39c
      action_button_down_short:
      - service: light.turn_off
        data: {}
        target:
          device_id:
          - 14ddd32c9da6f63ca83b15c67893d39c
          - e0f3a3bb6e76f1202e79a7d8f150ae72
- id: '1675650842209'
  alias: Remote - Living room
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      controller_device: 2d40199eb308c0b8485a578eb71d0ae6
      action_button_center_long: []
      integration: ZHA
      action_button_up_short:
      - service: light.turn_on
        data:
          color_temp: 500
        target:
          entity_id: light.dinning
      action_button_down_short: []
      helper_last_controller_event: input_text.helper_last_controller_event
- id: '1675706978863'
  alias: Remote - Living Room
  description: ''
  use_blueprint:
    path: niro1987/zha_ikea_tradfri_5button_remote_color.yaml
    input:
      remote: 2d40199eb308c0b8485a578eb71d0ae6
      light: light.dinning
      speed: 700
- id: '1675712102921'
  alias: Snapthot camera on motion
  description: ''
  use_blueprint:
    path: Stan-Gobien/CriticalCollapseOptionNotHomeMotionCameraSnapshotWithClickAction.yaml
    input:
      camera: camera.g3_instant_high
      notify_device: 8f9acfe8f9f171021d6a5fdc091c2c2c
      blocker_entity: device_tracker.sm_a54
      delay: 2
      is_ios: false
      motion_sensor: binary_sensor.g3_instant_motion
- id: '1676051186006'
  alias: Remote On/Off Media
  description: Speakers Sub and volume control
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: ad4998a1565e19ef225ab63c7f5fecb7
      action_button_up_short:
      - type: turn_on
        device_id: 0182288c04ac68aa5525e3a5b92c2b0d
        entity_id: switch.speakers_switch
        domain: switch
      - type: turn_on
        device_id: a381c9daa65b06ad6880514155d14369
        entity_id: switch.subwoofer_switch
        domain: switch
      action_button_up_long:
      - service: media_player.volume_up
        data: {}
        target:
          area_id: living_room
      action_button_down_short:
      - type: turn_off
        device_id: 0182288c04ac68aa5525e3a5b92c2b0d
        entity_id: switch.speakers_switch
        domain: switch
      - type: turn_off
        device_id: a381c9daa65b06ad6880514155d14369
        entity_id: switch.subwoofer_switch
        domain: switch
      helper_last_controller_event: input_text.helper_last_controller_event
      action_button_up_double:
      - service: media_player.media_next_track
        data: {}
        target:
          area_id: living_room
      action_button_down_long:
      - service: media_player.volume_down
        data: {}
        target:
          area_id: living_room
      action_button_down_double:
      - service: media_player.media_pause
        data: {}
        target:
          area_id: living_room
- id: '1676345626300'
  alias: Zone notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.tanya
      zone_entity: zone.home
      notify_device: 8f9acfe8f9f171021d6a5fdc091c2c2c
- id: '1676497123736'
  alias: 01 wake up test
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: 06:25:00
      light_entity: light.philips_1746547p7_huelight
      end_brightness: 255
      sunrise_duration: 15
      post_sunrise_actions:
      - device_id: 8f9acfe8f9f171021d6a5fdc091c2c2c
        domain: mobile_app
        type: notify
        message: 'Wake up :) '
      - service: media_player.play_media
        target: {}
        data:
          media_content_id: ''
          media_content_type: ''
        metadata: {}
      min_mired: 155
      check_entity: device_tracker.sm_a54
- id: '1676695352325'
  alias: System - Plex Recently Added
  description: Sensor attribute backup
  trigger:
  - platform: state
    entity_id:
    - sensor.plex_recently_added
    to: Online
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state not in [trigger.from_state.state, ''cannot
      be reached'', ''unavailable'', ''undefined'',''unknown'',''none'',''null'']
      }}'
  action:
  - service: input_text.set_value
    data:
      value: "{% if not states('sensor.plex_recently_added') in ['unavailable','undefined','unknown','none','null','0']
        %}\n  {% set state = namespace(return='') %}\n  {% set data = state_attr('sensor.plex_recently_added','data')
        %}\n  {%- for value in data %}\n    {%- if not loop.first and value is defined
        and state.return == '' %}\n      {%- if not value.number is defined %}\n        {%
        set state.return = \n          \"aired:\" + value.aired + \"|\" +\n          \"title:\"
        + value.title  + \"|\" +\n          \"fanart:\" + value.fanart + \"|\" +\n
        \         \"poster:\" + value.poster\n        %}\n      {%- else %}\n        {%
        set state.return = \n          \"aired:\" + value.aired + \"|\" +\n          \"title:\"
        + value.title  + \"|\" +\n          \"number:\" + value.number  + \"|\" +\n
        \         \"fanart:\" + value.fanart + \"|\" +\n          \"poster:\" + value.poster\n
        \       %}\n      {%- endif %}\n    {%- endif %}\n  {%- endfor %}\n  {{ state.return
        }}\n{% endif %}"
    target:
      entity_id: input_text.backup_plex_recently_added
  mode: single
- id: '1676712254087'
  alias: Managing a door contact
  description: ''
  use_blueprint:
    path: marco-hacs/managing_a_door_contact.yaml
    input:
      light: light.table_front_light
      light_off: 100
      door: binary_sensor.samjin_multi_accelerometer
      tts: true
      notify_device: 8f9acfe8f9f171021d6a5fdc091c2c2c
      push: true
      text_notify: The Front Door is Open
      notify_tts: []
      alexa: false
      notify_alexa: []
      time_door: 120
- id: '1676928639326'
  alias: 02 MEDIA - Node off on paused for x Min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.node_8adc
    to: paused
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - aec8f1a01101150430bf1d65e8f07486
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.node_8adc
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.node_8adc
  mode: single
- id: '1677093926789'
  alias: 02 Node ON on Source with conditions
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.node_8adc
    to: playing
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from: idle
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.node_8adc
        attribute: source
        state: TV (HDMI)
      sequence:
      - type: turn_on
        device_id: aec8f1a01101150430bf1d65e8f07486
        entity_id: switch.radio_switch
        domain: switch
      - service: media_player.volume_set
        data:
          volume_level: 0.5
        target:
          entity_id: media_player.node_8adc
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.node_8adc
        attribute: media_content_type
        state: music
      sequence:
      - type: turn_on
        device_id: aec8f1a01101150430bf1d65e8f07486
        entity_id: switch.radio_switch
        domain: switch
      - service: media_player.volume_set
        data:
          volume_level: 0.25
        target:
          entity_id: media_player.node_8adc
  mode: single
- id: '1677275238517'
  alias: 02 MEDIA - Node and Speakers OFF when SAMSUNG OFF
  description: ''
  trigger:
  - platform: device
    device_id: b91b22daad37db70b37adb9db8fc445c
    domain: media_player
    entity_id: media_player.samsung_55
    type: turned_off
  condition:
  - condition: state
    entity_id: media_player.node_8adc
    attribute: source
    state: TV (HDMI)
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.node_8adc
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - aec8f1a01101150430bf1d65e8f07486
    enabled: false
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.node_8adc
  mode: single
- id: '1677446975316'
  alias: 01 Light - Bedroom Hue with Controller
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      helper_last_controller_event: input_text.helper_last_controller_event
      controller_device: f9d2f322fa859bf1755236be155554b8
      action_button_down_long:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: light
        entity_id: light.philips_1746547p7_huelight
        type: brightness_decrease
      action_button_up_short:
      - type: turn_on
        device_id: c8448a875d206fae98aa1a00ff63ac69
        entity_id: light.philips_1746547p7_huelight
        domain: light
      action_button_up_long:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: light
        entity_id: light.philips_1746547p7_huelight
        type: brightness_increase
      action_button_up_double:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: number
        entity_id: number.philips_1746547p7_start_up_current_level
        type: set_value
        value: 128
        enabled: false
      action_button_down_short:
      - type: turn_off
        device_id: c8448a875d206fae98aa1a00ff63ac69
        entity_id: light.philips_1746547p7_huelight
        domain: light
      action_button_down_release: []
- id: '1681259486649'
  alias: Office check motion during day
  description: ''
  use_blueprint:
    path: Aleks130699/motion_light_brightness.yaml
    input:
      motion_entity: binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion
      on_night_time: '16:00:00'
      off_night_time: 06:00:00
      day_brightness: 0
      no_motion_wait_day: 20
      no_motion_wait_night: 180
      light_target:
        device_id: 14ddd32c9da6f63ca83b15c67893d39c
      night_brightness: 100
- id: '1681813776518'
  alias: Camera alert
  description: ''
  use_blueprint:
    path: Stan-Gobien/CriticalCollapseOptionNotHomeMotionCameraSnapshotWithClickAction.yaml
    input:
      motion_sensor: binary_sensor.g3_instant_motion
      camera: camera.g3_instant_high
      notify_device: 8f9acfe8f9f171021d6a5fdc091c2c2c
      delay: 1
      blocker_entity: person.lulu
- id: '1681813984075'
  alias: Door Open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.samjin_multi_accelerometer
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_a54
    data:
      title: 'The door was opened '
  mode: single
- id: '1681815049707'
  alias: Motion camera tanya
  description: ''
  use_blueprint:
    path: Stan-Gobien/CriticalCollapseOptionNotHomeMotionCameraSnapshotWithClickAction.yaml
    input:
      motion_sensor: binary_sensor.g3_instant_motion
      camera: camera.g3_instant_high
      notify_device: 43c813b68c7f421a12deccff613a91b1
- id: '1682890701443'
  alias: '00: Wake up alarm Workdays'
  description: Alarm Bedroom Sunrise, TTS on G3 and Kitchen Lights
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: 07:10:00
      light_entity: light.philips_1746547p7_huelight
      sunrise_duration: 10
      post_sunrise_actions:
      - service: notify.mobile_app_sm_a54
        data: {}
      - service: tts.cloud_say
        data:
          cache: false
          entity_id: media_player.g3_instant_speaker
          message: Its time to make some coffee
        enabled: false
      - type: turn_on
        device_id: 880cdcb176ca512d24055f43824dbf34
        entity_id: light.kitchen_led_switch
        domain: light
        enabled: true
      timestamp_sensor: none
      start_brightness: 5
      min_mired: 0
- id: '1698077798146'
  alias: '03 Smart toaster '
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: f55c47f5d4f9f6f2810e8eeb3a00fa0c
    entity_id: b0fab07f5cec9d47a39b41b23e45e765
    domain: switch
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 3
      seconds: 10
      milliseconds: 0
  - type: turn_off
    device_id: f55c47f5d4f9f6f2810e8eeb3a00fa0c
    entity_id: b0fab07f5cec9d47a39b41b23e45e765
    domain: switch
  mode: single
