- id: '1675371731836'
  alias: Remote - office
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: c50534a46a69819899bb017cf8a173b5
      action_button_up_short:
      - service: light.turn_on
        data: {}
        target:
          device_id: 34f3a2ff40e728c2c518d87ea9de74f2
      action_button_down_short:
      - service: light.turn_off
        data: {}
        target:
          device_id: 34f3a2ff40e728c2c518d87ea9de74f2
- id: '1675650842209'
  alias: Remote - Living room
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      controller_device: 2d40199eb308c0b8485a578eb71d0ae6
      action_button_center_long: []
      integration: ZHA
      action_button_up_short:
      - service: light.turn_on
        data:
          color_temp: 500
        target:
          entity_id: light.table_group
      action_button_down_short: []
      helper_last_controller_event: input_text.helper_last_controller_event
- id: '1675706978863'
  alias: Remote - Living Room
  description: ''
  use_blueprint:
    path: niro1987/zha_ikea_tradfri_5button_remote_color.yaml
    input:
      remote: 2d40199eb308c0b8485a578eb71d0ae6
      light: light.table_group
      speed: 700
- id: '1675712102921'
  alias: Snapthot camera on motion
  description: ''
  use_blueprint:
    path: Stan-Gobien/CriticalCollapseOptionNotHomeMotionCameraSnapshotWithClickAction.yaml
    input:
      camera: camera.g3_instant_high
      notify_device: 37ed3fa06bd2ae91f3c47d6cdc447356
      blocker_entity: zone.home
      delay: 2
      is_ios: false
      motion_sensor: binary_sensor.g3_instant_motion
- id: '1676051186006'
  alias: Remote On/Off Media
  description: Speakers Sub and volume control
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: ad4998a1565e19ef225ab63c7f5fecb7
      action_button_up_short:
      - type: turn_on
        device_id: 0182288c04ac68aa5525e3a5b92c2b0d
        entity_id: switch.speakers_switch
        domain: switch
      - type: turn_on
        device_id: a381c9daa65b06ad6880514155d14369
        entity_id: switch.subwoofer_switch
        domain: switch
      action_button_up_long:
      - service: media_player.volume_up
        data: {}
        target:
          area_id: living_room
      action_button_down_short:
      - type: turn_off
        device_id: 0182288c04ac68aa5525e3a5b92c2b0d
        entity_id: switch.speakers_switch
        domain: switch
      - type: turn_off
        device_id: a381c9daa65b06ad6880514155d14369
        entity_id: switch.subwoofer_switch
        domain: switch
      helper_last_controller_event: input_text.helper_last_controller_event
      action_button_up_double:
      - service: media_player.media_next_track
        data: {}
        target:
          area_id: living_room
      action_button_down_long:
      - service: media_player.volume_down
        data: {}
        target:
          area_id: living_room
      action_button_down_double:
      - service: media_player.media_pause
        data: {}
        target:
          area_id: living_room
- id: '1676345626300'
  alias: Zone notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.tanya
      zone_entity: zone.home
      notify_device: 2d5fc0e59ac365b406795e6114b6a24b
- id: '1676497123736'
  alias: 01 wake up test
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: 09:00:00
      timestamp_sensor: sensor.s7_edge_next_alarm
      check_entity: device_tracker.s7_edge
      light_entity: light.philips_1746547p7_huelight
      sunrise_duration: 5
      end_brightness: 96
- id: '1676695352325'
  alias: System - Plex Recently Added
  description: Sensor attribute backup
  trigger:
  - platform: state
    entity_id:
    - sensor.plex_recently_added
    to: Online
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state not in [trigger.from_state.state, ''cannot
      be reached'', ''unavailable'', ''undefined'',''unknown'',''none'',''null'']
      }}'
  action:
  - service: input_text.set_value
    data:
      value: "{% if not states('sensor.plex_recently_added') in ['unavailable','undefined','unknown','none','null','0']\
        \ %}\n  {% set state = namespace(return='') %}\n  {% set data = state_attr('sensor.plex_recently_added','data')\
        \ %}\n  {%- for value in data %}\n    {%- if not loop.first and value is defined\
        \ and state.return == '' %}\n      {%- if not value.number is defined %}\n\
        \        {% set state.return = \n          \"aired:\" + value.aired + \"|\"\
        \ +\n          \"title:\" + value.title  + \"|\" +\n          \"fanart:\"\
        \ + value.fanart + \"|\" +\n          \"poster:\" + value.poster\n       \
        \ %}\n      {%- else %}\n        {% set state.return = \n          \"aired:\"\
        \ + value.aired + \"|\" +\n          \"title:\" + value.title  + \"|\" +\n\
        \          \"number:\" + value.number  + \"|\" +\n          \"fanart:\" +\
        \ value.fanart + \"|\" +\n          \"poster:\" + value.poster\n        %}\n\
        \      {%- endif %}\n    {%- endif %}\n  {%- endfor %}\n  {{ state.return\
        \ }}\n{% endif %}"
    target:
      entity_id: input_text.backup_plex_recently_added
  mode: single
- id: '1676712254087'
  alias: Managing a door contact
  description: ''
  use_blueprint:
    path: marco-hacs/managing_a_door_contact.yaml
    input:
      light: light.table_front_light
      light_off: 100
      door: binary_sensor.samjin_multi_iaszone
      tts: true
      notify_device: 37ed3fa06bd2ae91f3c47d6cdc447356
      push: true
      text_notify: The Front Door is Open
      notify_tts:
      - media_player.g3_instant_speaker
      alexa: false
      notify_alexa: []
      time_door: 60
- id: '1676928639326'
  alias: 02 MEDIA - Node off on paused for x Min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.node_8adc
    to: paused
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - ba3f289f4f281ea4902ca90cca0b9f17
      - aec8f1a01101150430bf1d65e8f07486
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.node_8adc
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.node_8adc
  mode: single
- id: '1677093926789'
  alias: 02 Node ON on Source with conditions
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.node_8adc
    to: playing
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.node_8adc
        attribute: source
        state: TV (HDMI)
      sequence:
      - type: turn_on
        device_id: aec8f1a01101150430bf1d65e8f07486
        entity_id: switch.radio_switch
        domain: switch
      - type: turn_on
        device_id: ba3f289f4f281ea4902ca90cca0b9f17
        entity_id: switch.subwoofer_switch
        domain: switch
      - service: media_player.volume_set
        data:
          volume_level: 0.15
        target:
          entity_id: media_player.node_8adc
  mode: single
- id: '1677275238517'
  alias: 02 MEDIA - Node and Speakers OFF when SAMSUNG OFF
  description: ''
  trigger:
  - platform: device
    device_id: b91b22daad37db70b37adb9db8fc445c
    domain: media_player
    entity_id: media_player.samsung_55
    type: turned_off
  condition:
  - condition: state
    entity_id: media_player.node_8adc
    attribute: source
    state: TV (HDMI)
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.node_8adc
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - aec8f1a01101150430bf1d65e8f07486
      - ba3f289f4f281ea4902ca90cca0b9f17
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.node_8adc
  mode: single
- id: '1677446975316'
  alias: 01 Light - Bedroom Hue with Controller
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      helper_last_controller_event: input_text.helper_last_controller_event
      controller_device: f9d2f322fa859bf1755236be155554b8
      action_button_down_long:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: light
        entity_id: light.philips_1746547p7_huelight
        type: brightness_decrease
      action_button_up_short:
      - type: turn_on
        device_id: c8448a875d206fae98aa1a00ff63ac69
        entity_id: light.philips_1746547p7_huelight
        domain: light
      action_button_up_long:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: light
        entity_id: light.philips_1746547p7_huelight
        type: brightness_increase
      action_button_up_double:
      - device_id: c8448a875d206fae98aa1a00ff63ac69
        domain: number
        entity_id: number.philips_1746547p7_start_up_current_level
        type: set_value
        value: 128
        enabled: false
      action_button_down_short:
      - type: turn_off
        device_id: c8448a875d206fae98aa1a00ff63ac69
        entity_id: light.philips_1746547p7_huelight
        domain: light
      action_button_down_release: []
- id: '1681259486649'
  alias: Office check mption during day
  description: ''
  use_blueprint:
    path: Aleks130699/motion_light_brightness.yaml
    input:
      motion_entity: binary_sensor.ikea_of_sweden_tradfri_motion_sensor_motion
      on_night_time: '23:00:00'
      off_night_time: 06:00:00
      day_brightness: 50
      no_motion_wait_day: 20
      no_motion_wait_night: 30
      light_target:
        device_id: 4c394ec74b5d7fc064416fa60bb6b6ad
