light:
  - platform: group
    name: living_room_group
    entities:
      - light.table_front_light
      - light.table_back_light
      - light.coffee
      - light.couch
      - light.kitchen_led_switch

  - platform: group
    name: studio_group
    entities:
      - light.office_desk
      - light.studio_light_switch

  - platform: group
    name: bedroom_group
    entities:
      - light.philips_1746547p7_huelight

  - platform: group
    name: others_group
    entities:
      - light.coffee
      - light.balcony_switch

  #   - platform: group
  #     name: badrum_group
  #     entities:
  #       - light.badrum_vask_1
  #       - light.badrum_vask_2

  #   - platform: group
  #     name: hall_group
  #     entities:
  #       - light.hall_spot_1
  #       - light.hall_spot_2
  #       - light.hall_spot_3

  # - platform: group
  #   name: all_group_exclude_hall
  #   entities:
  #     - light.table_front_light
  #     - light.table_back_light
  #     - light.coffee
  #     - light.couch
  #     - light.kitchen_led_switch

  - platform: group
    name: all_lights_group
    entities:
      - light.living_room_group
      - light.studio_group
      - light.bedroom_group
      - light.others_group

switch:
  - platform: group
    name: all_devices_besides_nas
    entities:
      - switch.led_strip_switch
      - switch.radio_switch
# media:
#   - platform: group
#     name: all_media_players
#     entities:
#       - media_player.chromecast
#       - media_player.living_room_tv
#       - media_player.samsung_55

homeassistant:
  customize:
    light.living_room_group:
      friendly_name: Living Room #Belysning
#     light.studio_dator:
#       friendly_name: Datorlampa
#     light.studio_group:
#       friendly_name: Taklampor
#     light.sovrum_group:
#       friendly_name: Sänglampor
#     light.badrum_group:
#       friendly_name: Bathroom #Badrum
#     light.hall_group:
#       friendly_name: Hallampor
#     sensor.dimmer_badrum_battery_level:
#       friendly_name: Dimmer Badrum
#     sensor.dimmer_sovrum_battery_level:
#       friendly_name: Dimmer Sovrum
#     sensor.sensor_hall_battery:
#       friendly_name: Sensor Hall
#     sensor.sensor_garderob_battery:
#       friendly_name: Sensor Garderob
#     sensor.sensor_badrum_battery:
#       friendly_name: Sensor Badrum
