homeassistant:
  customize:
    person.lulu:
      entity_picture: /local/lulu.png
    device_tracker.s7_edge:
      entity_picture: /local/device_tracker.svg
    person.tanya:
      entity_picture: /local/tanya.png

person:
  - name: Lulu 
    id: lulu
    device_trackers:
      - device_tracker.s7_edge #device_tracker.mattias_iphone_unifi
      - device_tracker.galaxy_s7_edge #UNIFY

  - name: Tanya
    id: tanya
    device_trackers:
      - device_tracker.tanya_phone #device_tracker.tanyas_iphone_unifi
      - device_tracker.oneplus_nord_ce_2 #UNIFY

mqtt:
  sensor:
    - name: lulu_last_changed
      state_topic: homeassistant/persistence/lulu
      value_template: >
        {{ value | replace(' ', 'T') }}

    - name: tanya_last_changed
      state_topic: homeassistant/persistence/tanya
      value_template: >
        {{ value | replace(' ', 'T') }}

automation:
  - alias: person_home
    id: '8423590985012'
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.lulu
        - person.tanya
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.name | lower }}
        payload_template: >
          {{ now() }}
        retain: true

