# scene:
#   #TODO
#   - name: home_below_horizon
#     entities:
#       light.studio_dator:
#         state: 'on'
#   - name: home_above_horizon
#     entities:
#       light.studio_dator:
#         state: 'on'

script:
  home_arrive:
    alias: Home #Hemma
    sequence:
      - if:
          condition: state
          entity_id: sun.sun
          state: below_horizon
        then:
          service: scene.turn_on
          target:
            entity_id: scene.home_below_horizon
        else:
          service: scene.turn_on
          target:
            entity_id: scene.home_above_horizon
      - delay:
          seconds: 4

  home_leave:
    alias: All Off #Stäng allt
    sequence:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - light.all_group_exclude_hall
            - climate.ac
            - media_player.bedroom_tv
            - media_player.samsung_55
            - switch.bedroom_switch
            - switch.balcony_switch
            - switch.subwoofer_switch
            - switch.radio_switch
      - delay:
          seconds: 4
