update_entities:
  action: >
    [[[
      hass.callService('homeassistant', 'update_entity', {
          entity_id: [
            'sensor.udm_unifios'
          ]
      });
    ]]]
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Security Overview
    card_mod:
      style:
        #popup header
        .:
    content:
      type: vertical-stack
      cards:
        - type: entities
          state_color: true
          card_mod:
            class: content
          entities:
            - entity: binary_sensor.g3_instant_motion
              secondary_info: last-changed

            - entity: binary_sensor.hallway_motion_sensor
              secondary_info: last-changed

            - entity: binary_sensor.studio_motion_sensor
              secondary_info: last-changed

            - entity: weather.forecast_home
              secondary_info: last-changed

            - entity: device_tracker.w11
              secondary_info: last-changed

            - entity: sensor.192_168_1_5_tccd1_temperature
              name: CPU Temperature

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: "%"
              positions:
                icon: outside
                indicator: "off"
                name: outside
              severity:
                - color: "#6d2525"
                  from: 90
                  to: 999
              entity_row: true
              entities:
                - entity: sensor.tautulli_watching
                - entity: sensor.192_168_1_5_mnt_system_cache_used_percent
                - entity: sensor.192_168_1_5_tccd1_temperature

            - entity: sensor.udm_pro_uptime

        - type: custom:mod-card
          card_mod:
            style:
              hui-horizontal-stack-card$: |
                #root {
                  justify-content: space-evenly !important;
                  padding: var(--tablet-popup-button-padding);
                }
          card:
            type: horizontal-stack
            cards:
              - type: custom:button-card
                name: Network devices
                icon: mdi:devices
                tap_action:
                  action: url
                  url_path: https://192.168.1.1/network/default/clients
                template: icon_name

              - type: custom:button-card
                name: System
                icon: mdi:cog
                tap_action:
                  action: url
                  url_path: https://192.168.1.1/settings/system
                template: icon_name
